version: '3.8'

services:
  digital-twin:
    build: .
    container_name: energy_supply_twin
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app  # Allows for live-reloading during local development
